### ISSUE TITLE
Bot Repeating the same Images !

### ISSUE THREAD

**Issue by vteam27** [vteam27/RIF-bot#1]
- Sometimes the bot sends the same image more than once, for example- 
 
![image](https://user-images.githubusercontent.com/94956831/184553044-060dc33e-b72b-4be3-8be5-820829fcf318.png)

- I would appreciate it if someone can build something that solves this maybe like an image URL logging system (or Hashing) to keep track of sent images and prevent the bot from repeating those images without reducing the number of images output to the user.

- You probably wanna work inside the ./commands/fetch.js file .

**Comment by marinoffDev** [comment]
Hey @vteam27 I'll give this a shot :)
